### ISSUE TITLE
Use PDO instead of mysqli

### ISSUE THREAD

**Issue by ntimo** [userjack6880/Open-DMARC-Analyzer#1]
Hello,
the project looks very very awesome. But I have one small question, why are you using mysqli instead of PDO? :) PDO supports much more databases types.

Best wishes,
Timo

**Comment by userjack6880** [comment]
I appreciate the feedback. I honestly hadn't considered PDO - I've been using mysqli (and by extension, mysqli) for so long, I guess I just haven't moved on. I'll actually give it a consideration and do some testing with it.

**Comment by userjack6880** [comment]
I've taken your suggestion and implemented PDO instead of mysqli. Once again, thanks for the attention and suggestion.
