### ISSUE TITLE
Where shall the XML of DMARC report be?

### ISSUE THREAD

**Issue by Dragane** [userjack6880/Open-DMARC-Analyzer#10]
Hi, 

i dont know, where to place the DMARC report XML file. Shouldn't there be some sort of the upload button, where you could do this? How exactly should i use this tool?

**Comment by userjack6880** [comment]
Per the Readme, you need to use [John Levine's rrdmarc script](https://www.taugh.com/rddmarc/) or [techsneeze's dmarcts-report-parser](https://github.com/techsneeze/dmarcts-report-parser) and connect to the databases created by those scripts. This tool simply gives you a visual output of the data that gets generated by those scripts.
