### ISSUE TITLE
[Question]: End Of Life

### ISSUE THREAD

**Issue by m4djack** [userjack6880/Open-DMARC-Analyzer#107]
Just a question regarding End of Life, we are going to test this out but I just wonder if will be a new version soon or what will happen with end of life in December 2024.

**Comment by userjack6880** [comment]
I do plan on having a new version out sometime in May. However, if I do miss this goal, the EOS and EOL will be updated.

**Comment by m4djack** [comment]
Thanks! I will close this :)

**Comment by killerbees19** [comment]
@userjack6880 Ping? 🙂
