### ISSUE TITLE
Add colours to the report (domain.php)

### ISSUE THREAD

**Issue by ntimo** [userjack6880/Open-DMARC-Analyzer#3]
Hello,
when viewing the domain.php for one domain it is quite hard to see which reports failed and which passed. Maybe it would be good to add a bit of colour to be able to see this more clearly.

<img width="200" alt="Screenshot 2019-06-21 at 18 06 33" src="https://user-images.githubusercontent.com/6145026/59936149-9a167100-944f-11e9-89e6-2a1f4bff3aeb.png">

Best wishes,
Timo

**Comment by userjack6880** [comment]
Definitely will consider this.

**Comment by userjack6880** [comment]
Alpha 5 added colors for pass and fail.
