### ISSUE TITLE
Option to sort by reporting org

### ISSUE THREAD

**Issue by ntimo** [userjack6880/Open-DMARC-Analyzer#4]
Hello,
I would be amazing if you could sort by reporting org, so that you can for example see all reports that google send at a glance.

Best wishes,
Timo

**Comment by userjack6880** [comment]
Like on the tables that show up under each domain, or as a separate section? You can sort each table currently by clicking on the headers (some fields are not sortable). There's plans in the works for just a reporting org page.

**Comment by userjack6880** [comment]
This is a feature already built into the way tables can be sorted via the UI.
