### ISSUE TITLE
Set date range via UI

### ISSUE THREAD

**Issue by ntimo** [userjack6880/Open-DMARC-Analyzer#5]
Hello,
it would be awesome to be able to set the date range via the web ui this would make browsing the latest reports much easier. Now you would have to edit the config.php on the server to change this.

Maybe a date picker where you can simply select a month or a custom date range or of course all would be nice.

Best wishes,
Timo

**Comment by userjack6880** [comment]
There was an existing ability to add a GET option to the url to change when the date starts. I still haven't written anything for the end date, but that'll eventually get included. Right now, it's more useful to see things from x date up until today.

The range option is set in number of weeks (it's the only thing I support right now, will add days and months later). For example: index.php?range=2w

Alpha 4 has added a control that lets you set the starting date back/forwards a week. It's a bit clumsy, but will work for now.

**Comment by ntimo** [comment]
I have to say I really like to new 1 week back/forwards system, but this could maybe be made configurable via the config.php so that you can set the default time range for this. So it can maybe be more then just 1 week. I didn't know that using `index.php?range=2w` was possible this is defiantly nice.

**Comment by userjack6880** [comment]
How configurable on the config file do you mean? Like what parameter - how many weeks it goes back or the default start period?

**Comment by ntimo** [comment]
If you take a look at the config in the master branch I would simply use to define the default period that the fowards/backwards button uses. This way it can be -1 one week or even -2 months 
```
define('DATE_RANGE', '-1 week');
```

**Comment by userjack6880** [comment]
I know it's been nearly 2 years since this was last addressed. Finally coming around to this issue - you can put in there '-1 month' to define a default of 4 weeks. I do realize that there is a minor bug that when you click <- 1 Week or 1 Week ->, it seems to consider the 1 week default only. This will be corrected in the next dev update.

**Comment by userjack6880** [comment]
Update: test the new function in the dev branch, see if that suits your needs.
