### ISSUE TITLE
[Bug]: Can't create table dmarc.reports

### ISSUE THREAD

**Issue by burtiraven** [userjack6880/Open-DMARC-Analyzer#60]
I have a vps with runcloud and clone the repository and configure db but time to create a tables in db not create table name dmarc.reports

**Comment by burtiraven** [comment]
https://dmarc.burti.one/index.php
I create a tables and columns necessary but no look for upload an XML archives! Help!

**Comment by userjack6880** [comment]
I've been unavailable for the past week or so. If you can provide more details? Did you install either of the other requirements that create most of the tables for you?

https://www.taugh.com/rddmarc/
https://github.com/techsneeze/dmarcts-report-parser

The view created with this requires those tables to pre-exist in those projects. This only presents the data generated from those other projects in an easier to view way. It does not import xml data itself.

**Comment by userjack6880** [comment]
Closing since this was not a true bug.
