### ISSUE TITLE
[Bug]: Division by zero

### ISSUE THREAD

**Issue by jadethaveekij** [userjack6880/Open-DMARC-Analyzer#68]
At certain times (certain weeks), it seemed that there is this error.  Not sure if this is related to the data part?

Warning: Division by zero in /var/web/mrtg/dmarc/Open-DMARC-Analyzer/includes/template.php on line 280
Warning: Division by zero in /var/web/mrtg/dmarc/Open-DMARC-Analyzer/includes/template.php on line 281
Warning: Division by zero in /var/web/mrtg/dmarc/Open-DMARC-Analyzer/includes/template.php on line 282
Warning: Division by zero in /var/web/mrtg/dmarc/Open-DMARC-Analyzer/includes/template.php on line 283
Warning: Division by zero in /var/web/mrtg/dmarc/Open-DMARC-Analyzer/includes/template.php on line 284

Somewhere along this 

  // stat calculations
  $dmarc_comp_pct = number_format(100 * ($dmarc_comp / $dmarc_none));
  $dkim_comp_pct  = number_format(100 * ($dkim_pass_aligned / $dmarc_none));
  $dkim_pass_pct  = number_format(100 * (($dkim_pass_aligned + $dkim_pass_noalign) / $dmarc_none));
  $spf_comp_pct   = number_format(100 * ($spf_pass_aligned  / $dmarc_none));
  $spf_pass_pct   = number_format(100 * (($spf_pass_aligned  + $spf_pass_noalign)  / $dmarc_none));

![2022-11-08 17_11_26-Open DMARC Analyzer - Dashboard and 2 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/24450273/200537539-b1e3efa3-a339-45cc-a9db-bb6e39c90d94.png)

**Screenshots**

**Software Version**
1-fc upgraded from 0-α7.1

**Comment by userjack6880** [comment]
Seems to be a case where if there are 0 accepted emails, it literally is trying to divide by zero. It'll get addressed in the next update. I'll leave this open until it's addressed.

**Comment by jadethaveekij** [comment]
yes, this is some old, legacy domains which we need to only keep a few mails for delivery -- and it was marked as a subdomains so it's mostly ... spamtraped domains T__T"  sorry for the troubles.

**Comment by userjack6880** [comment]
Can you give the version in the dev branch a try and see if this solves your issue? It should be a straightforward fix from 1-fc.

**Comment by jadethaveekij** [comment]
Confirmed that the reported issue is now fixed.    THANK YOU.  ==/|\==

Below two screenshots are based on the same data range -- I had to change the date range much shorter (1d) to view/find the issue.  

before:
![image](https://user-images.githubusercontent.com/24450273/204419677-363e1961-a49c-4182-8987-fd94ec70886a.png)

after:
![image](https://user-images.githubusercontent.com/24450273/204419730-62fbe15f-0fe3-41b6-a2f6-951a00ddec42.png)

**Comment by userjack6880** [comment]
Exactly what I like to hear. Thanks!
