### ISSUE TITLE
[Question]: DB issues when i try to install

### ISSUE THREAD

**Issue by AlexPBrin** [userjack6880/Open-DMARC-Analyzer#76]
cant install keep getting an error with the Db

connecting to database... success
opening file... success
→ CREATE VIEW IF NOT EXISTS report_stats AS (
→ SELECT
→ report.serial, domain, rcount, disposition, reason,
→ policy_p, policy_pct, dkimdomain, dkimresult, dkim_align,
→ spfdomain, spfresult, spf_align, mindate, maxdate
→ FROM report RIGHT JOIN rptrecord
→ ON report.serial=rptrecord.serial
→ );
performing query... failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dmarc3456.rptrecord' doesn't exist

**Comment by maisen20** [comment]
Yes, there are really some problems. Also I see some security concerns with the whole folder structure.

**Comment by userjack6880** [comment]
The database issue is that you do not have a pre-req installed. No tables are created, instead views are created from pre-existing tables created by either rrdmarc or dmarcs-report-parser. 

> A database that is pre-populated with data from rrdmarc or dmarcts-report-parser

maisen20, please create a new issue with your security concerns

**Comment by Smiley3112** [comment]
Sorry to open an old discussion, but I have the same errors. I do not understand what you mean by "pre-req not installed". 

I've followed all the instructions in the readme and also installed the missing json dependancy.

**Comment by MatthewHana** [comment]
> Sorry to open an old discussion, but I have the same errors. I do not understand what you mean by "pre-req not installed".
> 
> I've followed all the instructions in the readme and also installed the missing json dependancy.

This project is a visualisation and analysis tool for a database populated by this project: https://github.com/techsneeze/dmarcts-report-parser

You need to have configured and run that parser first so that it can create the tables in your database and populate them.
